import type { NextPage } from "next";
import { useEffect, useState } from "react";
import Head from "next/head";
import Image from "next/image";
import { Navbar } from "../src/components/Navbar/Navbar";
import { ArtistCover } from "../src/components/ArtistCover/ArtistCover";
import { CreateAccount } from "../src/components/CreateAccount/CreateAccount";
import styles from "../src/styles/Home.module.css";
import { IArtist } from "../src/models/Artist"

const Home: NextPage = () => {
  const [artist, setArtist] = useState<any>();
  
  useEffect(() => {
    const getArtist = async () => {
      const ids = ["627b35d06c3d09b9e456712a", "627b35f76c3d09b9e456712c", "627b13796c3d09b9e45670da"]
      const randomNum = await Math.round(Math.random() * (2 - 0) + 0);
      const response = await fetch(`https://rockstars8g-backend.herokuapp.com/artist/${ids[randomNum]}`);
      const artistInfo: IArtist = await response.json();
      setArtist(artistInfo)
    }
    getArtist()
  }, []);

  return (
    // <div className={styles.container}>
    //   <Head>
    //     <title>Create Next App</title>
    //     <meta name="description" content="Generated by create next app" />
    //     <link rel="icon" href="/favicon.ico" />
    //   </Head>

    //   <main className={styles.main}>
    //     <h1 className={styles.title}>
    //       Welcome to <a href="https://nextjs.org">Next.js!</a>
    //     </h1>

    //     <p className={styles.description}>
    //       Get started by editing{' '}
    //       <code className={styles.code}>pages/index.tsx</code>
    //     </p>

    //     <div className={styles.grid}>
    //       <a href="https://nextjs.org/docs" className={styles.card}>
    //         <h2>Documentation &rarr;</h2>
    //         <p>Find in-depth information about Next.js features and API.</p>
    //       </a>

    //       <a href="https://nextjs.org/learn" className={styles.card}>
    //         <h2>Learn &rarr;</h2>
    //         <p>Learn about Next.js in an interactive course with quizzes!</p>
    //       </a>

    //       <a
    //         href="https://github.com/vercel/next.js/tree/canary/examples"
    //         className={styles.card}
    //       >
    //         <h2>Examples &rarr;</h2>
    //         <p>Discover and deploy boilerplate example Next.js projects.</p>
    //       </a>

    //       <a
    //         href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
    //         className={styles.card}
    //       >
    //         <h2>Deploy &rarr;</h2>
    //         <p>
    //           Instantly deploy your Next.js site to a public URL with Vercel.
    //         </p>
    //       </a>
    //     </div>
    //   </main>

    //   <footer className={styles.footer}>
    //     <a
    //       href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
    //       target="_blank"
    //       rel="noopener noreferrer"
    //     >
    //       Powered by{' '}
    //       <span className={styles.logo}>
    //         <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
    //       </span>
    //     </a>
    //   </footer>
    // </div>
    <>
      <Head>
        <title>Renify | Home page</title>
        <meta name="description" content="Music store for Rockstars Generation 8G by Renata Hurtado Moreno" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar type="home"></Navbar>
      <ArtistCover artist={artist}></ArtistCover>
      <CreateAccount />
    </>
  )
}

export default Home
